"""Update Dev model with relationships

Revision ID: 0420e2b0bcf6
Revises: bd3a1c6d4871
Create Date: 2025-11-30 12:45:59.948988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0420e2b0bcf6'
down_revision = 'bd3a1c6d4871'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
